[package]
name = "boost_process"
description = "Boost C++ library boost_process packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_process"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_process"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_algorithm = { version = "0.1.0", path = "../boost_algorithm" }
boost_asio = { version = "0.1.0", path = "../boost_asio" }
boost_assert = { version = "0.1.0", path = "../boost_assert" }
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_core = { version = "0.1.0", path = "../boost_core" }
boost_filesystem = { version = "0.1.0", path = "../boost_filesystem" }
boost_fusion = { version = "0.1.0", path = "../boost_fusion" }
boost_io = { version = "0.1.0", path = "../boost_io" }
boost_iterator = { version = "0.1.0", path = "../boost_iterator" }
boost_move = { version = "0.1.0", path = "../boost_move" }
boost_optional = { version = "0.1.0", path = "../boost_optional" }
boost_system = { version = "0.1.0", path = "../boost_system" }
boost_throw_exception = { version = "0.1.0", path = "../boost_throw_exception" }
boost_tokenizer = { version = "0.1.0", path = "../boost_tokenizer" }
boost_type_index = { version = "0.1.0", path = "../boost_type_index" }
boost_type_traits = { version = "0.1.0", path = "../boost_type_traits" }
boost_utility = { version = "0.1.0", path = "../boost_utility" }
boost_winapi = { version = "0.1.0", path = "../boost_winapi" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
